#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
#define U_NP KC_NO // key is not present
#define U_NA KC_NO // present but not available for use
#define U_NU KC_NO // available but not used

enum layers { COLEMAK, NAV, NUM, SYM, FUN, MBO, MEDIA, MOUSE};

#define U_RDO SCMD(KC_Z)
#define U_PST LCMD(KC_V)
#define U_CPY LCMD(KC_C)
#define U_CUT LCMD(KC_X)
#define U_UND LCMD(KC_Z)

#define LCONTROL LCTL_T(KC_A)
#define LOPTION LALT_T(KC_R)
#define LCOMMAND LGUI_T(KC_S)
#define LSHIFT LSFT_T(KC_T)
#define RSHIFT RSFT_T(KC_N)
#define RCOMMAND RGUI_T(KC_E)
#define ROPTION RALT_T(KC_I)
#define RCONTROL RCTL_T(KC_O)

#define MEDIA_ESC LT(MEDIA, KC_ESC)
#define NAV_TAB   LT(NAV, KC_TAB)
#define MOUSE_SPC LT(MOUSE, KC_SPC)
#define SYM_ENT   LT(SYM, KC_ENT)
#define NUM_BSPC  LT(NUM, KC_BSPC)
#define FUN_DEL   LT(FUN, KC_DEL)
#define FUN_K     LT(FUN, KC_K)

const uint16_t PROGMEM esc_combo[] = {NAV_TAB, MOUSE_SPC, COMBO_END};
const uint16_t PROGMEM fun_combo[] = {SYM_ENT, NUM_BSPC, COMBO_END};
const uint16_t PROGMEM cpslk_combo[] = {LCONTROL, RCONTROL, COMBO_END};
combo_t key_combos[] = {
    COMBO(esc_combo, MEDIA_ESC),
    COMBO(fun_combo, FUN_DEL),
    COMBO(cpslk_combo, KC_CAPS),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [COLEMAK] = LAYOUT(
      //,------------------------------------------------.                         ,-------------------------------------------------.
           KC_Q,    KC_W,     KC_F,    KC_P,     KC_G,                               KC_J,     KC_L,     KC_U,    KC_Y,     KC_QUOT,
      //|----------+--------+--------+----------+--------|                         |---------+---------+---------+---------+---------|
           LCONTROL,LOPTION, LCOMMAND, LSHIFT,   KC_D,                               KC_H,     RSHIFT,   RCOMMAND, ROPTION, RCONTROL,
      //|----------+--------+--------+----------+--------|                         |---------+---------+---------+---------+---------|
            KC_Z,    KC_X,     KC_C,     KC_V,    KC_B,                              FUN_K,      KC_M,   KC_COMM,  KC_DOT,   KC_SLSH,
      //|----------+--------+--------+----------+--------+------------|  |---------+---------+---------+---------+---------+---------|
                                                  NAV_TAB, MOUSE_SPC,      SYM_ENT, NUM_BSPC
                                           //`------------------------'  `---------------------'
    ),

  [NAV] = LAYOUT(
        //,----------------------------------------------.                    ,--------------------------------------------.
               U_NA,   U_NA,    U_NA,    U_NA,    U_NA,                          U_NA, U_PST,   U_CPY,   U_CUT,   U_UND,
        //|----------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------|
              KC_LCTL, KC_LALT,  KC_LGUI, KC_LSFT, U_NA,                          U_NA, KC_LEFT, KC_DOWN, KC_UP,  KC_RGHT,
        //|----------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------|
               U_NA,    KC_ALGR, U_NA,    U_NA,    U_NA,                          U_NA, KC_HOME, KC_PGDN, KC_PGUP, KC_END,
        //|----------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------|
                                                   U_NA,    U_NA,      KC_ESC, KC_DEL
                                     //`--------------------------'  `--------------------------'
  ),
  [NUM] = LAYOUT(
        //,--------------------------------------------.                    ,----------------------------------------------.
            KC_LBRC,  KC_7,    KC_8,    KC_9,  KC_RBRC,                        U_NA,    U_NA,    U_NA,    U_NA,   U_NA,
        //|--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+-|
            KC_SCLN,  KC_4,    KC_5,    KC_6,   KC_EQL,                        U_NA,   KC_LSFT, KC_LGUI, KC_LALT, KC_LCTL,
        //|--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+-|
            KC_GRV,   KC_1,    KC_2,    KC_3,   KC_BSLS,                       U_NA,   U_NA,    U_NA,   KC_ALGR,  U_NA,
        //|--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+-|
                                                KC_0,  KC_MINS,      U_NA,    U_NA
                                   //`--------------------------'  `--------------------------'
  ),
  [SYM] = LAYOUT(
        //,---------------------------------------------.                    ,-----------------------------------------------.
            KC_LCBR, KC_AMPR, KC_ASTR, KC_LPRN,  KC_RCBR,                      U_NA,    U_NA,    U_NA,    U_NA,    U_NA,
        //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+---------------|
            KC_COLN, KC_DLR,  KC_PERC, KC_CIRC, KC_PLUS,                        U_NA,   KC_LSFT,   KC_LGUI, KC_LALT, KC_LCTL,
        //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+---------------|
            KC_TILD, KC_EXLM, KC_AT,   KC_HASH, KC_PIPE,                       U_NA,    U_NA,    U_NA,    KC_ALGR, U_NA,
        //|---------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+---------------|
                                                 KC_MINS, KC_UNDS,      U_NA,     U_NA
                                             //`-----------------'  `--------------------------'
  ),
  [FUN] = LAYOUT(
        //,---------------------------------------------.                    ,---------------------------------------------.
             KC_F12,  KC_F7,   KC_F8,   KC_F9,  KC_PSCR,                        U_NA,    U_NA,    U_NA,    U_NA,  U_NA,
        //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+---------|
             KC_F11,  KC_F4,   KC_F5,   KC_F6,   KC_SCROLL_LOCK,                U_NA,  KC_LSFT, KC_LGUI, KC_LALT, KC_LCTL,
        //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+---------|
             KC_F10,  KC_F1,   KC_F2,   KC_F3,  KC_PAUS,                        U_NA,     U_NA,  U_NA,    KC_ALGR, U_NA,
        //|---------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+---------|
                                                KC_LPRN,  KC_RPRN,      U_NA,    U_NA
                                             //`-----------------'  `--------------------------'
  ),
  [MBO] = LAYOUT(
       //,---------------------------------------------.                    ,----------------------------------------------.
           KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                       KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
       //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+------------|
           KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_TRNS,                       KC_TRNS, KC_LGUI, KC_LSFT, KC_LCTL, KC_LALT,
       //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+------------|
           U_RDO,   U_PST,   U_CPY,   U_CUT,   U_UND,                         U_RDO,   U_PST,   U_CPY,   U_CUT,   U_UND,
       //|---------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+------------|
                                               KC_BTN3, KC_BTN1,     KC_BTN1, KC_BTN3
                                            //`-----------------'  `--------------------------'
  ),
  [MEDIA] = LAYOUT(
        //,---------------------------------------------.                    ,-----------------------------------------------.
              U_NA,   U_NA,    U_NA,    U_NA,    U_NA,                         RGB_TOG, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI,
        //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--|
             KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, U_NA,                         U_NU,    KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT,
        //|---------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--|
             U_NA,    KC_ALGR, U_NA,    U_NA,    U_NA,                         U_NU,    U_NU,    U_NU,    U_NU,    U_NU,
        //|---------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--|
                                                U_NA,    U_NA,        KC_MSTP, KC_MUTE
                                             //`-----------------'  `----------------- '
  ),
  [MOUSE] = LAYOUT(
        //,--------------------------------------------.                    ,-----------------------------------------------.
            U_NA,   U_NA,    U_NA,    U_NA,    U_NA,                         U_PST,   U_CPY,   U_CUT,   U_UND,  U_RDO,
        //|--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+-------------|
            KC_LCTL, KC_LALT,  KC_LGUI, KC_LSFT, U_NA,                         U_NU,    KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R,
        //|--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+-------------|
            KC_P,    KC_ALGR, U_NA,    U_NA,    U_NA,                         U_NU,    KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R,
        //|--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+-------------|
                                                U_NA,    U_NA,       KC_BTN1, KC_BTN3
                                             //`----------------'  `-----------------'
  )
};

void keyboard_pre_init_user(void) {
  // Set our LED pin as output
  setPinOutput(24);
  // Turn the LED off
  // (Due to technical reasons, high is off and low is on)
  writePinHigh(24);
}

void caps_word_set_user(bool active) {
  setPinOutput(24);
  if (active) {
      writePinLow(24);
  } else {
      writePinHigh(24);
  }
}
